// <auto-generated />
using System;
using Domain.Customers;
using Domain.Destino;
using Domain.Paquete;
using Domain.Reserva;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity<Customer>(b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("Active")
                    .HasColumnType("bit");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("PhoneNumber")
                    .IsRequired()
                    .HasMaxLength(9)
                    .HasColumnType("nvarchar(9)");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.ToTable("Customers", (string)null);
            });

            modelBuilder.Entity<Destino>(b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                // Properties for Destino entity

                b.HasKey("Id");

                b.ToTable("Destinos", (string)null);
            });

            modelBuilder.Entity<Paquete>(b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                // Properties for Paquete entity

                b.HasKey("Id");

                b.ToTable("Paquetes", (string)null);
            });

            modelBuilder.Entity<Reserva>(b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                // Properties for Reserva entity

                b.HasKey("Id");

                b.ToTable("Reservas", (string)null);
            });

#pragma warning restore 612, 618
        }
    }
}
